name: dashboard-couting-consul-failover

services:
  consul:
    image: hashicorp/consul:1.19
    entrypoint:
      - consul
    command:
      - agent
      - -server
      - -bootstrap-expect=1
      - -node=consul-failover-1
      - -ui
      - -client=0.0.0.0
      - -bind=0.0.0.0
      - -data-dir=/consul/data
      - -config-dir=/consul/config
    ports:
      - "18500:8500"
      - "18600:8600/tcp"
      - "18600:8600/udp"
    volumes:
      - ./consul-failover:/consul/config:ro
      - consul-failover-data:/consul/data
    networks:
      failover-network:
        ipv4_address: 172.31.0.2

  counting-service-1:
    image: winyannainghtut/counting-service:latest
    build: ./counting-service
    ports:
      - "9101:9001"
    environment:
      - PORT=9001
      - STORAGE_MODE=memory
    depends_on:
      - consul
    networks:
      failover-network:
        ipv4_address: 172.31.0.3

  counting-service-2:
    image: winyannainghtut/counting-service:latest
    build: ./counting-service
    ports:
      - "9102:9001"
    environment:
      - PORT=9001
      - STORAGE_MODE=memory
    depends_on:
      - consul
    networks:
      failover-network:
        ipv4_address: 172.31.0.5

  dashboard-service:
    image: winyannainghtut/dashboard-service:latest
    build: ./dashboard-service
    ports:
      - "9100:9002"
    environment:
      - PORT=9002
      - COUNTING_SERVICE_URL=http://counting.service.consul:9001
      - CONSUL_DNS_ADDR=consul:8600
    depends_on:
      - consul
      - counting-service-1
      - counting-service-2
    networks:
      failover-network:
        ipv4_address: 172.31.0.4

networks:
  failover-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24

volumes:
  consul-failover-data:
